:PROPERTIES:
:ID:       a4b3f2c8-1135-408e-a2e8-e9ce8ab161d9
:END:
#+TITLE: README: Learn in public

* What is this?

This is a bunch of [[https://www.orgroam.com/][org-roam]]
files where I write notes in an attempt
to [[https://www.learninpublic.org/][learn in public]].

* Why are the file names weird?

The file names are generated by ~org-roam-node-*~,
and are meant to prevent name collisions
in a large set of org-roam notes.

But that also means that this repository will be harder to
navigate outside of org-roam itself. That's a trade-off I'm
deciding to make for now, as this repository is not exactly
a proper publishing target (i.e. pages aren't meant to look
pretty).

Keeping this set of defaults also means that
these files can be dropped
into most org-roam setups with minimal fuss.

If you want to make navigating these files easier,
clone this repository and set it up as an
[[https://github.com/zeddee/learn-in-public/blob/20b259d5c3c93ab8d1529378893dc4439a0e11a8/20220129152140-emacs_notes.org#create-a-new-and-isolated-org-roam-directory][isolated org-roam directory]].

* License

 All work in this repository © 2022 by Zed Tan is licensed under
 Attribution-NonCommercial-NoDerivatives 4.0 International.
 To view a copy of this license, visit
 http://creativecommons.org/licenses/by-nc-nd/4.0/
